version: '3.9'
services:
  redis-master:
    image: bitnami/redis
    hostname: redis-master
    networks:
      - redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_REPLICATION_MODE=master
    deploy:
      replicas: 1

  redis-slave:
    image: bitnami/redis
    hostname: redis-slave-{{.Task.Slot}}
    networks:
      - redis
    depends_on:
      - redis-master
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_REPLICA_IP=redis-slave-{{.Task.Slot}}
    deploy:
      replicas: 3
      placement:
        max_replicas_per_node: 1

  redis-sentinel:
    image: bitnami/redis-sentinel
    networks:
      - redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=3000
      - REDIS_MASTER_HOST=redis-master
    deploy:
      mode: global
    depends_on:
      - redis-master
#   healthcheck:
#     test: ["CMD", "redis-sentinel", "--test", "mymaster"]
#     interval: 10s
#     timeout: 5s
#     retries: 3

  proxy:
    image: haproxy:2.9.6-alpine
    hostname: redis
    configs:
      - source: haproxy
        target: /usr/local/etc/haproxy/haproxy.cfg
    networks:
      - redis
    depends_on:
      - redis-sentinel
#         condition: service_healthy

networks:
  redis:
    name: redis
    external: true

configs:
  haproxy:
    file: ./haproxy.cfg
