target: all,ruler,alertmanager,overrides-exporter

server:
  http_listen_port: 3100
  grpc_listen_port: 9095
  log_level: info
  # Configure the server to allow messages up to 100MB.
  grpc_server_max_recv_msg_size: 1048576000
  grpc_server_max_send_msg_size: 1048576000
  grpc_server_max_concurrent_streams: 10000

limits:
  max_label_names_per_series: 35

memberlist:
  join_members: [mimir-1, mimir-2, mimir-3]
  advertise_addr: ADVERTISE_ADDR_REPLACE

common:
  storage:
    backend: s3
    s3:
      endpoint: minio:9000
      access_key_id: jUATwbv7K6x1NfryfGpm
      secret_access_key: ULUhIqZf2HOKt1mtHCfezopGeXFCnKOx73YT4XmT
      insecure: true
      bucket_name: mimir

# Blocks storage requires a prefix when using a common object storage bucket.
blocks_storage:
  s3:
    bucket_name: mimir-blocks

ruler_storage:
  s3:
    bucket_name: mimir-ruler

alertmanager_storage:
  s3:
    bucket_name: mimir-alertmanager

