---
- name: Install firewalld
  become: true
  ansible.builtin.package:
    name: firewalld
    state: present

- name: Start firewalld service
  become: true
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true

- name: Enable basic firewall rules
  become: true
  ansible.posix.firewalld:
    service: "{{ item.service }}"
    port: "{{ item.port }}"
    protocol: "{{ item.protocol }}"
    state: "{{ item.state }}"
    immediate: true
    permanent: true
  notify: Restart firewalld
  loop:
    - { service: ssh, port: '{{ ssh_port }}', protocol: tcp, state: enabled }
    - { service: http, port: 80, protocol: tcp, state: enabled }
    - { service: https, port: 443, protocol: tcp, state: enabled }

- name: Configure firewalld for Docker Swarm
  become: true
  ansible.posix.firewalld:
    port:
      - 2377/tcp
      - 7946/tcp
      - 7946/udp
      - 4789/udp
    permanent: true
    state: enabled
  notify: Restart firewalld
  tags: swarm
