---
- name: Install firewalld
  become: true
  ansible.builtin.package:
    name: firewalld
    state: present

- name: Start firewalld service
  become: true
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true

- name: Enable basic firewall rules
  become: true
  ansible.posix.firewalld:
    port: "{{ item.port }}/{{ item.protocol }}"
    state: "{{ item.state }}"
    immediate: true
    permanent: true
  notify: Restart firewalld
  loop:
    - { port: '{{ ssh_port }}', protocol: tcp, state: enabled }
    - { port: 80, protocol: tcp, state: enabled }
    - { port: 443, protocol: tcp, state: enabled }

- name: Configure firewalld for Docker Swarm
  become: true
  ansible.posix.firewalld:
    port: "{{ item.port }}/{{ item.protocol }}"
    state: "{{ item.state }}"
    immediate: true
    permanent: true
  notify: Restart firewalld
  loop:
    - { port: 2377, protocol: tcp, state: enabled }
    - { port: 7946, protocol: tcp, state: enabled }
    - { port: 7946, protocol: udp, state: enabled }
    - { port: 4789, protocol: udp, state: enabled }
  tags: swarm
