services:
  pg:
    image: bitnami/postgresql-repmgr:16
    hostname: pg-1
    volumes:
      - pg_data:/bitnami/postgresql
    networks:
      - pg_net
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=${POSTGRESQL_POSTGRES_PASSWORD}
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - REPMGR_PASSWORD=${REPMGR_PASSWORD}
      - REPMGR_PRIMARY_HOST=pg-1
      - REPMGR_PARTNER_NODES=pg-1,pg-2
      - REPMGR_NODE_NAME=pg-1
      - REPMGR_NODE_NETWORK_NAME=pg-1

  pg-2:
    image: bitnami/postgresql-repmgr:16
    hostname: pg-2
    volumes:
      - pg_data-2:/bitnami/postgresql
    networks:
      - pg_net
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=${POSTGRESQL_POSTGRES_PASSWORD}
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - REPMGR_PASSWORD=${REPMGR_PASSWORD}
      - REPMGR_PRIMARY_HOST=pg-1
      - REPMGR_PARTNER_NODES=pg-1,pg-2
      - REPMGR_NODE_NAME=pg-2
      - REPMGR_NODE_NETWORK_NAME=pg-2

  pgpool:
    image: bitnami/pgpool:4
    hostname: db
    networks:
      - pg_net
    environment:
      - PGPOOL_BACKEND_NODES=0:pg-1:5432,1:pg-2:5432
      - PGPOOL_SR_CHECK_USER=${POSTGRESQL_USERNAME}
      - PGPOOL_SR_CHECK_PASSWORD=${POSTGRESQL_PASSWORD}
      - PGPOOL_ENABLE_LDAP=no
      - PGPOOL_POSTGRES_USERNAME=postgres
      - PGPOOL_POSTGRES_PASSWORD=${POSTGRESQL_POSTGRES_PASSWORD}
      - PGPOOL_ADMIN_USERNAME=${PGPOOL_ADMIN_USERNAME}
      - PGPOOL_ADMIN_PASSWORD=${PGPOOL_ADMIN_PASSWORD}
    depends_on:
      - pg
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/pgpool/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5

  pg-backup:
    image: postgres:16-alpine
    volumes:
      - pg_backup:/backup
      - pg_data:/var/lib/postgresql/data:ro
    networks:
      - pg_net
    environment:
      - POSTGRES_USER=${POSTGRESQL_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRES_DB=${POSTGRESQL_DATABASE}
    command: ["sh", "-c", "echo '5 0 * * * /usr/bin/pg_dump -U $$POSTGRES_USERNAME -d $$POSTGRES_DATABASE > /backup/backup.sql' > /etc/crontabs/root && crond -f -L /dev/stdout"]
    depends_on:
      - pgpool

volumes:
  pg_data:
    name: pg_data
  pg_data-2:
    name: pg_data-2
  pg_backup:
    name: pg_backup

networks:
  pg_net:
    external: true
    name: pg_net
