services:
  pg:
    image: bitnami/postgresql-repmgr:16
    hostname: pg-{{.Task.Slot}}
    volumes:
      - pg_data:/bitnami/postgresql
    networks:
      - pg_net
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=${POSTGRESQL_POSTGRES_PASSWORD}
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - REPMGR_PASSWORD=${REPMGR_PASSWORD}
      - REPMGR_PRIMARY_HOST=pg-1
      - REPMGR_PARTNER_NODES=pg-1,pg-2
      - REPMGR_NODE_NAME=pg-{{.Task.Slot}}
      - REPMGR_NODE_NETWORK_NAME=pg-{{.Task.Slot}}
    deploy:
      replicas: 2
      placement:
        max_replicas_per_node: 1

  pgpool:
    image: bitnami/pgpool:4
    hostname: db
    networks:
      - pg_net
    environment:
      - PGPOOL_BACKEND_NODES=0:pg-1:5432,1:pg-2:5432
      - PGPOOL_SR_CHECK_USER=${POSTGRESQL_USERNAME}
      - PGPOOL_SR_CHECK_PASSWORD=${POSTGRESQL_PASSWORD}
      - PGPOOL_ENABLE_LDAP=no
      - PGPOOL_POSTGRES_USERNAME=postgres
      - PGPOOL_POSTGRES_PASSWORD=${POSTGRESQL_POSTGRES_PASSWORD}
      - PGPOOL_ADMIN_USERNAME=${PGPOOL_ADMIN_USERNAME}
      - PGPOOL_ADMIN_PASSWORD=${PGPOOL_ADMIN_PASSWORD}
    depends_on:
      - pg

volumes:
  pg_data:
    name: pg_data

networks:
  pg_net:
    external: true
    name: pg_net
