version: '3.9'
services:
  vote:
    image: dockersamples/examplevotingapp_vote
    hostname: vote-server
    command: python app.py
    networks:
      - traefik-net
      - redis
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-net"
        - "traefik.http.routers.vote.entrypoints=http"
        - "traefik.http.routers.vote.rule=Host(`vote.arman.fun`)"
        - "traefik.http.routers.vote.middlewares=https-redirect"
        - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.vote-secure.entrypoints=https"
        - "traefik.http.routers.vote-secure.rule=Host(`vote.arman.fun`)"
        - "traefik.http.routers.vote-secure.tls=true"
        - "traefik.http.routers.vote-secure.tls.certresolver=mycert"
        - "traefik.http.services.vote.loadbalancer.server.port=80"

  worker:
    image: dockersamples/examplevotingapp_worker
    networks:
      - redis
      - pg_net

  result:
    image: dockersamples/examplevotingapp_result
    networks:
      - traefik-net
      - pg_net
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-net"
        - "traefik.http.routers.result.entrypoints=http"
        - "traefik.http.routers.result.rule=Host(`result.arman.fun`)"
        - "traefik.http.routers.result.middlewares=https-redirect"
        - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.result-secure.entrypoints=https"
        - "traefik.http.routers.result-secure.rule=Host(`result.arman.fun`)"
        - "traefik.http.routers.result-secure.tls=true"
        - "traefik.http.routers.result-secure.tls.certresolver=mycert"
        - "traefik.http.services.result.loadbalancer.server.port=80"

networks:
  traefik-net:
    name: traefik-net
    external: true
  redis:
    external: true
    name: redis_redis
  pg_net:
    external: true
    name: pg_net
