global:
  scrape_interval:     30s
  evaluation_interval: 30s
  external_labels:
    monitor: prom

rule_files:
  - /etc/prometheus/alerts/*.rules

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
        - alertmanager:9093

scrape_configs:
  - job_name: redis_exporter
    static_configs:
      - targets:
        - redis://redis-master:6379
        - redis://redis-slave1:6379
        - redis://redis-slave2:6379
        - redis://redis-sentinel:26379
    metrics_path: /scrape
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__meta_dockerswarm_node_hostname]
        target_label: instance
      - target_label: __address__
        replacement: redis-exporter:9121

  - job_name: 'postgres'
    static_configs:
      - targets:
        - pg-0:5432
        - pg-1:5432
    metrics_path: /probe
    params:
      user: [postgres]
      password: [postgres]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__meta_dockerswarm_node_hostname]
        target_label: instance
      - target_label: __address__
        replacement: postgres-exporter:9187

  - job_name: 'pgpool'
    static_configs:
    - targets: ['pgpool-exporter:9719']

  # Make Prometheus scrape itself for metrics.
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'docker'
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: nodes
    relabel_configs:
      # Fetch metrics on port 9323.
      - source_labels: [__meta_dockerswarm_node_address]
        target_label: __address__
        replacement: $1:9323
      # Set hostname as instance label
      - source_labels: [__meta_dockerswarm_node_hostname]
        target_label: instance

  - job_name: 'cadvisor'
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: tasks
    relabel_configs:
      - source_labels: [__meta_dockerswarm_service_name]
        regex: 'exporter_cadvisor'
        action: keep
      - source_labels: [__meta_dockerswarm_task_desired_state]
        regex: 'running'
        action: keep
      - source_labels: [__meta_dockerswarm_service_name]
        target_label: job
      - source_labels: [__meta_dockerswarm_node_hostname]
        target_label: instance
      - source_labels: [__address__]
        target_label: __address__
        regex: '(.*):(.*)'
        replacement: '$1:8080'
 
  - job_name: 'mimir'
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: tasks
    relabel_configs:
      - source_labels: [__meta_dockerswarm_service_name]
        regex: 'mimir_mimir'
        action: keep
      - source_labels: [__meta_dockerswarm_task_desired_state]
        regex: 'running'
        action: keep
      - source_labels: [__meta_dockerswarm_network_name]
        regex: 'prometheus'
        action: keep
      - source_labels: [__meta_dockerswarm_node_hostname]
        target_label: instance
      - source_labels: [__address__]
        target_label: __address__
        regex: '(.*):(.*)'
        replacement: '$1:3100'
 
  - job_name: 'node'
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: tasks
    relabel_configs:
      - source_labels: [__meta_dockerswarm_service_name]
        regex: 'exporter_node_exporter'
        action: keep
      - source_labels: [__meta_dockerswarm_task_desired_state]
        regex: 'running'
        action: keep
      - source_labels: [__meta_dockerswarm_node_hostname]
        target_label: instance
      - source_labels: [__address__]
        target_label: __address__
        regex: '(.*):(.*)'
        replacement: '$1:9100'

  - job_name: minio-job
    bearer_token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9tZXRoZXVzIiwic3ViIjoiYWRtaW4iLCJleHAiOjQ4NjUyNzgwNTd9._vkvNMqtJ0D0FTWT4AGMvsO3JphNNpUM6_69rm3JjJNFuIciON_kMh_75-6r9dECvsV3t1w36RvGdf9iZ5hvbA
    metrics_path: /minio/v2/metrics/cluster
    scheme: http
    static_configs:
    - targets: ['minio-1:9000', 'minio-2:9000']

  - job_name: 'pushgateway'
    scrape_interval: 30s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['pushgateway:9091']
    
remote_write:
  - url: http://mimir:3100/api/v1/push
    headers:
      X-Scope-OrgID: monster
