networks:
  minio:
    name: minio
    external: true
  traefik-net:
    external: true
  prometheus:
    external: true

volumes:
  minio-data-1:

services:
  minio:
    image: quay.io/minio/minio
    hostname: minio-1
    networks:
      - minio
      - traefik-net
      - prometheus
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    command: 
      - "server"
      - "--console-address"
      - ":9001"
      - "http://minio-{1...2}:9000/data1"
    volumes:
      - minio-data-1:/data1
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == sw1
      update_config:
        parallelism: 1
        delay: 30s
        order: stop-first
        failure_action: rollback
      rollback_config:
        parallelism: 1
        delay: 30s
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-net"
        - "traefik.http.routers.minio.entrypoints=http"
        - "traefik.http.routers.minio.rule=Host(`minio.arman.fun`)"
        - "traefik.http.routers.minio.middlewares=https-redirect"
        - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.minio-secure.entrypoints=https"
        - "traefik.http.routers.minio-secure.rule=Host(`minio.arman.fun`)"
        - "traefik.http.routers.minio-secure.tls=true"
        - "traefik.http.routers.minio-secure.tls.certresolver=mycert"
        - "traefik.http.services.minio.loadbalancer.server.port=9001"
  minio-2:
    image: quay.io/minio/minio
    hostname: minio-2
    networks:
      - minio
      - traefik-net
      - prometheus
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    command: 
      - "server"
      - "--console-address"
      - ":9001"
      - "http://minio-{1...2}:9000/data1"
    volumes:
      - minio-data-1:/data1
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == sw2
      update_config:
        parallelism: 1
        delay: 30s
        order: stop-first
        failure_action: rollback
      rollback_config:
        parallelism: 1
        delay: 30s
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-net"
        - "traefik.http.routers.minio.entrypoints=http"
        - "traefik.http.routers.minio.rule=Host(`minio.arman.fun`)"
        - "traefik.http.routers.minio.middlewares=https-redirect"
        - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.minio-secure.entrypoints=https"
        - "traefik.http.routers.minio-secure.rule=Host(`minio.arman.fun`)"
        - "traefik.http.routers.minio-secure.tls=true"
        - "traefik.http.routers.minio-secure.tls.certresolver=mycert"
        - "traefik.http.services.minio.loadbalancer.server.port=9001"
