networks:
  minio:
    name: minio
    external: true
  traefik-net:
    external: true

volumes:
  minio-data-1:

services:
  minio:
    image: quay.io/minio/minio
    hostname: minio-{{.Task.Slot}}
    networks:
      - minio
      - traefik-net
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    command: 
      - "server"
      - "--console-address"
      - ":9001"
      - "http://minio-{1...2}:9000/data1"
    volumes:
      - minio-data-1:/data1
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    #   interval: 30s
    #   timeout: 20s
    #   retries: 3
    deploy:
      replicas: 2
      placement:
        max_replicas_per_node: 1
      update_config:
        parallelism: 1
        delay: 30s
        order: stop-first
        failure_action: rollback
      rollback_config:
        parallelism: 1
        delay: 30s
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
      labels:
        - "logging=promtail"
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-net"
        - "traefik.http.routers.minio.entrypoints=http"
        - "traefik.http.routers.minio.rule=Host(`minio.arman.fun`)"
        - "traefik.http.routers.minio.middlewares=https-redirect"
        - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.minio-secure.entrypoints=https"
        - "traefik.http.routers.minio-secure.rule=Host(`minio.arman.fun`)"
        - "traefik.http.routers.minio-secure.tls=true"
        - "traefik.http.routers.minio-secure.tls.certresolver=mycert"
        - "traefik.http.services.minio.loadbalancer.server.port=9001"
